number_emojis:
  '1': '1️⃣'
  '2': '2️⃣'
  '3': '3️⃣'
  '4': '4️⃣'
  '5': '5️⃣'
  '6': '6️⃣'
  '7': '7️⃣'
  '8': '8️⃣'
  '9': '9️⃣'
  '0': '0️⃣'
emoji_numbers:
  '1️⃣': '1'
  '2️⃣': '2'
  '3️⃣': '3'
  '4️⃣': '4'
  '5️⃣': '5'
  '6️⃣': '6'
  '7️⃣': '7'
  '8️⃣': '8'
  '9️⃣': '9'
  '0️⃣': '0'
emoji_dict:
  "offline": '<:offline:689360441822150701>'
  "idle": '<:idle:689360441956499501>'
  "dnd": '<:dnd:689360442098843672>'
  "online": '<:online:689360442048643285>'
perm_list:
- 'manage_messages'
- 'create_instant_invite'
- 'kick_members'
- 'ban_members'
- 'administrator'
- 'manage_channels'
- 'manage_guild'
- 'add_reactions'
- 'view_audit_log'
- 'read_messages'
- 'send_messages'
- 'send_tts_messages'
- 'embed_links'
- 'attach_files'
- 'read_message_history'
- 'mention_everyone'
- 'external_emojis'
- 'view_guild_insights'
- 'change_nickname'
- 'manage_nicknames'
- 'manage_roles'
- 'manage_webhooks'
- 'manage_emojis'
- 'is_owner'
- 'dm_only'
- 'is_nsfw'
bad_perms:
- 'priority_speaker'
- 'stream'
- 'connect'
- 'speak'
- 'mute_members'
- 'deafen_members'
- 'move_members'
- 'use_voice_activation'
progress_bar:
  '0': '`[            ]`'
  '1': '`[ █          ]`'
  '2': '`[ ██         ]`'
  '3': '`[ ███        ]`'
  '4': '`[ ████       ]`'
  '5': '`[ █████      ]`'
  '6': '`[ ██████     ]`'
  '7': '`[ ███████    ]`'
  '8': '`[ ████████   ]`'
  '9': '`[ █████████  ]`'
  '10': '`[ ██████████ ]`'